/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewGameRouteImport } from './routes/new-game'
import { Route as IndexRouteImport } from './routes/index'

const NewGameRoute = NewGameRouteImport.update({
  id: '/new-game',
  path: '/new-game',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/new-game': typeof NewGameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/new-game': typeof NewGameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/new-game': typeof NewGameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/new-game'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/new-game'
  id: '__root__' | '/' | '/new-game'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewGameRoute: typeof NewGameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/new-game': {
      id: '/new-game'
      path: '/new-game'
      fullPath: '/new-game'
      preLoaderRoute: typeof NewGameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewGameRoute: NewGameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
